config/routes.rb
KladrOnRails::Application.routes.draw do

  get '/kladr', to: 'kladr#index', as: 'kladr'
  get 'kladr/:code', to: 'kladr#show', as: 'kladr_show'
  get 'street/:code', to: 'kladr#street', as: 'kladr_street'
  get 'doma/:code', to: 'kladr#doma', as: 'kladr_doma'

  

end

app/models/doma.rb
class Doma < ActiveRecord::Base
  self.table_name = "DOMA"
  establish_connection(YAML.load_file(File.join(Rails.root, 'config', 'database.yml'))['kladr'])
end

app/models/kladr.rb
class Kladr < ActiveRecord::Base
  self.table_name = "kladr"
  establish_connection(YAML.load_file(File.join(Rails.root, 'config', 'database.yml'))['kladr'])

  # СС РРР ГГГ ППП АА
  # SS RRR GGG PPP AA

  # выборка регионов (первый уровень иерархии) подумать как по-другому
  # scope :regions, where("code REGEXP ?", "^[[:digit:]][[:digit:]]+00000000000")
  # scope :regions, where("code LIKE ?", "__00000000000")
  # scope :regions, select{ |region| region.code[2..12] == "00000000000"}

  def self.regions
    where("code LIKE ?", "__00000000000")
  end


  # TODO как-то сделать по-человечески
  def children
    case code
    when /^\d{2}0*$/
      parent_code = code[0..1]
      Kladr.where("code != ? AND (code LIKE ? OR code LIKE ? OR code LIKE ?)",
        "#{parent_code}00000000000", "#{parent_code}___00000000", "#{parent_code}000___00000", "#{parent_code}000000___00")
    when /^\d{5}0*$/
      parent_code = code[0..4]
      Kladr.where("code != ? AND (code LIKE ? OR code LIKE ?)",
        "#{parent_code}00000000", "#{parent_code}___00000", "#{parent_code}000___00")
    when /^\d{8}0*$/
      parent_code = code[0..7]
      Kladr.where("code != ? AND code LIKE ?",
        "#{parent_code}00000", "#{parent_code}___00")
    end
  end

  def parent
    if code =~ /^\d{2}0*$/
      nil
    elsif (code =~ /^\d{5}0*$/) || (code =~ /^\d{2}000\d{3}0*$/) || (code =~ /^\d{2}000000\d{3}0*$/)
      Kladr.where("code LIKE ?", "#{code[0..1]}00000000000").first
    elsif (code =~ /^\d{8}0*$/) || (code =~ /^\d{5}000\d{3}0*$/)
      Kladr.where("code LIKE ?", "#{code[0..4]}00000000").first
    elsif (code =~ /^\d{11}0*$/)
      Kladr.where("code LIKE ?", "#{code[0..7]}00000").first
    end
  end

  def parents
    parent = self.parent
    while !parent.nil? do
      parents = [parent] + (parents || [])
      parent = parent.parent
    end
    parents || []
  end

  # TODO заменить на отношения 1 ко многим
  def street
    Street.where("code LIKE ?", "#{code[0..10]}____00")
  end

  # TODO заменить на отношения 1 ко многим
  def doma
    Doma.where("code LIKE ?", "#{code[0..10]}0000____")
  end

  def level
    case code
    when /^\d{2}0*$/
      '1'
    when /^\d{5}0*$/
      '2'
    when /^\d{8}0*$/
      '3'
    when /^\d{11}0*$/
      '4'
    end
  end

  def title
    name + ' ' + VOCABULARY[level][socr]
  end
  # вот как-то так надо, но пока не получилось
  # has_many :street, :class_name => 'Street', :conditions => '( STREET.code LIKE ? = "#{code[0..10]}____00"'



  # TODO потом перенести чтобы был виден и другим моделям
  # возможно и не нужен ужеы
  # def parent_code #(code)
    # case code
    # when /^\d{2}0*$/
      # code[0..1]
    # when /^\d{5}0*$/
      # code[0..4]
    # when /^\d{8}0*$/
      # code[0..7]
    # when /^\d{11}0*$/
      # code[0..10]
    # end
  # end



# Посмотреть!!!
# http://railsapps.github.io/twitter-bootstrap-rails.html
# https://github.com/RailsApps/rails-bootstrap
# https://github.com/anjlab/bootstrap-rails/issues/53
# http://stackoverflow.com/questions/18371318/installing-bootstrap-3-on-rails-app
# https://github.com/anjlab/bootstrap-rails

# посмотреть видеоуроки
# https://www.google.ru/#newwindow=1&q=rails%204.0%20twitter%20bootstrap%203%20tutorial&safe=off&tbs=qdr:y

end

app/models/socrbase.rb
class Socrbase < ActiveRecord::Base
  self.table_name = "socrbase"
  establish_connection(YAML.load_file(File.join(Rails.root, 'config', 'database.yml'))['kladr'])

  def self.vocabulary
    socrs = Socrbase.all
    levels = socrs.map(&:level).uniq #=> ["1", "2", "3", "4", "5", "6"]
    hash = Hash[levels.map {|v| [v,{}]}] #=> {"1"=>{}, "2"=>{}, "3"=>{}, "4"=>{}, "5"=>{}, "6"=>{}}
    socrs.each{|record| hash[record.level].merge!({record.scname => record.socrname}) }
    hash
  end
end

app/models/street.rb
class Street < ActiveRecord::Base
  self.table_name = "street"
  establish_connection(YAML.load_file(File.join(Rails.root, 'config', 'database.yml'))['kladr'])

  def doma
    Doma.where("code LIKE ?", "#{code[0..14]}____")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/kladr_controller.rb
class KladrController < ApplicationController
  def index
    @regions = Kladr.regions
  end

  def show
    @entity = Kladr.find_by_code(params[:code])
    @parents = @entity.parents
    @children = @entity.children
    @street = @entity.street
    @doma = @entity.doma
  end
  
  def street
    @entity = Street.find_by_code(params[:code])
    @doma = @entity.doma
  end
  
  def doma
    @entity = Doma.find_by_code(params[:code])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/kladr/doma.html.erb
<h1>Kladr#doma</h1>
<p>Find me in app/views/kladr/doma.html.erb</p>
<h2><%= @entity.name %></h2>

app/views/kladr/index.html.erb
<h1>Kladr#index</h1>
<p>Find me in app/views/kladr/index.html.erb</p>

<% unless @regions.blank? %>
  <% @regions.each do |region| %>
    <p>
      <%= region.code[0..1] %>
      <%= link_to region.title, kladr_show_path(:code => region.code) %>
      <%= region.code %>
    </p>
  <% end %>
<% end %>

app/views/kladr/show.html.erb
<h1>Kladr#show</h1>
<p>Find me in app/views/kladr/show.html.erb</p>

<p>
<%= link_to 'КЛАДР', kladr_path %>
<% if @parents.present? %>
  <% @parents.each do |parent| %>
    <%= link_to " / #{parent.title}", kladr_show_path(:code => parent.code) %>
  <% end %>
<% end %>
<%= " / #{@entity.title}" %>
</p>

<% unless @children.blank? %>
  <% @children.each do |child| %>
   <p><%#= link_to_if !(child.children.blank? && child.street.blank?), child.name, kladr_show_path(:code => child.code) %></p>
   <p><%= link_to child.title, kladr_show_path(:code => child.code) %></p>
  <% end %>
<% end %>

<h3>улицы</h3>
<% unless @street.blank? %>
  <% @street.each do |street| %>
   <p><%#= street.name %></p>
   <p><%= link_to street.name, kladr_street_path(:code => street.code) %></p>
  <% end %>
<% end %>

<h3>Дома</h3>
<% unless @doma.blank? %>
  <% @doma.each do |dom| %>
   <p><%#= street.name %></p>
   <p><%= link_to dom.name, kladr_doma_path(:code => dom.code) %></p>
  <% end %>
<% end %>

app/views/kladr/street.html.erb
<h1>Kladr#street</h1>
<p>Find me in app/views/kladr/street.html.erb</p>
<h2><%= @entity.name %></h2>


<% unless @doma.blank? %>
  <% @doma.each do |dom| %>
   <p><%#= link_to_if !(child.children.blank? && child.street.blank?), child.name, kladr_show_path(:code => child.code) %></p>
   <p><%#= link_to child.name, kladr_show_path(:code => child.code) %></p>
   <p><%= dom.name %></p>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KladrOnRails</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>